import styles from '../assets/styles/_export.scss';

export const {
  BREAKPOINT_LG,
  BREAKPOINT_MD,
  BREAKPOINT_SM,
  BREAKPOINT_XS,
  COLOR_GREY_BLUE,
  COLOR_MARINE_BLUE,
  FONT_POPPINS,
  FONT_POPPINS_BOLD,
  FONT_POPPINS_BOLD_ITALIC,
  FONT_POPPINS_ITALIC,
  FONT_POPPINS_SEMI_BOLD,
  WORK_PAGE_HEADER_HEIGHT,
  WORK_SLIDER_HEIGHT_SM,
  WORK_SLIDER_WIDTH,
  WORK_SLIDER_WIDTH_SM,
} = styles;

export const MEDIA_LG = 'MEDIA_LG';
export const MEDIA_MD = 'MEDIA_MD';
export const MEDIA_SM = 'MEDIA_SM';
export const MEDIA_XL = 'MEDIA_XL';
export const MEDIA_XS = 'MEDIA_XS';
